# Site settings
title: Sync Tab Groups
email: synctabgroups@gmail.com
url: https://morikko.github.io/synctabgroups/

urls:
  github: https://github.com/Morikko/sync-tab-groups
  firefox: https://addons.mozilla.org/en-US/firefox/addon/sync-tab-groups/
  chrome: #

description: "Sync Tab Groups is an easy way to manage all your tabs. You organize them depending on a topic by group. Groups can be closed and reopend without caring about your session. Moreover, you can esily search, active, move, save and remove your groups and tabs."
keywords: "workflow tabs organization browser"
meta_author: Morikko

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2aa1c0 # Home color
  primary-rgb: 0e647d # Portfolio hover
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Morikko
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Morikko/sync-tab-groups
  - title: firefox
    url: https://addons.mozilla.org/en-US/firefox/addon/sync-tab-groups/
  - title: chrome
    url: #

# Postal address (add as many lines as necessary)
address:
  - line:   '<label style="right: auto; left: 263px; top: 4px; margin: 0px;"><span class="fa fa-code" style="color:black;"></span> with <span class="fa fa-heart" style="color:red;"></span> from <img src="img/france_flag.png" alt="France"></label>'
  - line: '<label style="right: auto; left: 263px; top: 4px; margin: 0px;"> As an Open Source project.</label>'

# Credits content
credits: 'Based on the template <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer for jekyll</a>. Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.<br/>
Icons: <a href="https://www.freepik.com/free-vector/red-coming-soon-lettering_760449.htm">Freepik</a>'

# Build settings
markdown: kramdown
permalink: pretty
